export const metadata = {
  title: 'Playground of kacperwalter.com',
  description: 'Generated by create next app',
}

const Playground = () => {
  return (
    <div>There will be a beautiful playground stuff</div>
  )
}

export default Playground