import BlogFeed from "../components/BlogFeed/BlogFeed"

export const metadata = {
  title: 'Blog about frontend development | kacperwalter.com',
  description: 'Generated by create next app',
}

const BlogMainPage = () => {
  return (
    <BlogFeed />
  )
}

export default BlogMainPage